### ISSUE TITLE
Scale of the "create layers" window is incorrect

### ISSUE THREAD

**Issue by sargunv** [awkwardpolygons/better-texture-array#1]
![image](https://user-images.githubusercontent.com/1320357/113503014-2cccb680-94e4-11eb-9881-c8e032f22a55.png)

If I click on most ot the "format" dropdown, the window just closes because I'm clicking outside the bounds of the window.

Additionally, I can't click the "Create" button below it at all, since it has no overlap with the window bounds.

Switching Godot's display scale to 100% works around the issue, but ofc then [Godot's gui becomes tiny](https://user-images.githubusercontent.com/1320357/113503110-9f3d9680-94e4-11eb-931c-bfec913d20d3.png).
.

**Comment by arccoza** [comment]
Thanks, what version of Godot are you using and what res is your screen?

**Comment by sargunv** [comment]
Godot 3.2.3, and my display is 5120x2160 though my display scale is set to 150%.

**Comment by arccoza** [comment]
Thanks for the extra info, I'll dig into it.

**Comment by arccoza** [comment]
I pushed a fix, download the latest and let me know if it's good.
